config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root "projects#index"

  resources :projects do
    resources :tickets
  end

end

app/models/ability.rb
class Ability
  
  include CanCan::Ability
  
  def initialize(user)
    user.permissions.each do |permission|
      can permission.action.to_sym, permission.thing_type.constantize do |thing|
        thing.nil? || permission.thing_id.nil? || permission.thing_id == thing.id
      end
    end
  end
end

app/models/permission.rb
class Permission < ActiveRecord::Base
  belongs_to :user
  belongs_to :thing, polymorphic: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true

  has_many :tickets, dependent: :delete_all
  has_many :permissions, as: :thing

  scope :viewable_by, ->(user) do
    joins(:permissions).where(permissions: { action: "view", user_id: user.try(:id) })
  end

  scope :for, ->(user) do
    user.admin? ? Project.all : Project.viewable_by(user)
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
    
  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  scope :admin, -> { where(admin: true) }
  scope :by_name, -> { order(:name) }
  has_many :permissions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin!, except: [:index, :show]
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.for(current_user)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to @project
    else
      flash[:alert] = "Project has not been created."
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @project.update(project_params)
      flash[:notice] = "Project has been updated."
      redirect_to @project
    else
      flash[:alert] = 'Project has not been updated.'
      render 'edit'
    end
  end
  
  def destroy
    @project.destroy
    flash[:notice] = "Project has been destroyed."
    redirect_to projects_path
  end

  private

    def project_params
        params.require(:project).permit(:name, :description)
    end
    
    def set_project
      @project = Project.for(current_user).find(params[:id])

      rescue ActiveRecord::RecordNotFound
        flash[:alert] = "The project you were looking for could not be found."
        redirect_to projects_path
    end

    def require_admin!
      unless current_user.admin?
      flash[:alert] = "You must be an admin to do that."
      redirect_to root_path
      end
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :authorize_create!, only: [:new, :create]
  before_action :authorize_update!, only: [:edit, :update]
  before_action :authorize_delete!, only: :destroy

  def new
    @ticket = @project.tickets.build
    @ticket.user = current_user
  end

  def create
    @ticket = @project.tickets.build(ticket_params)
    @ticket.user = current_user
    if @ticket.save
      flash[:notice] = "Ticket has been created."
      redirect_to [@project, @ticket]
    else
      flash[:alert] = "Ticket has not been created."
      render "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @ticket.update(ticket_params)
      flash[:notice] = "Ticket has been updated."
      redirect_to [@project, @ticket]
    else
      flash[:alert] = "Ticket has not been updated."
      render action: "edit"
    end
  end

  def destroy
    @ticket.destroy
    flash[:notice] = "Ticket has been deleted."
    
    redirect_to @project
  end
  
  private
    
    def set_ticket
      @ticket = @project.tickets.find(params[:id])
    
      rescue ActiveRecord::RecordNotFound
        flash[:alert] = "The ticket you were looking for could not be found."
        redirect_to projects_path
    end

    def ticket_params
      params.require(:ticket).permit(:title, :description)
    end

    def set_project
      @project = Project.for(current_user).find(params[:project_id])
    
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The project you were looking for could not be found."
      redirect_to root_path
    end

    def authorize_create!
      if !current_user.admin? && cannot?("create tickets".to_sym, @project)
        flash[:alert] = "You cannot create tickets on this project."
        redirect_to @project
      end
    end

    def authorize_update!
      if !current_user.admin? && cannot?("edit tickets".to_sym, @project)
        flash[:alert] = "You cannot edit tickets on this project."
        redirect_to @project
      end
    end

    def authorize_delete!
      if !current_user.admin? && cannot?(:"delete tickets", @project)
        flash[:alert] = "You cannot delete tickets from this project."
        redirect_to @project
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admins_only(&block)
    block.call if current_user.try(:admin?)
  end
  
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "Ticketee").join(" - ")
      end
    end 
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <% if content_for?(:title) %>
      <%= yield(:title) %>
    <% else %>
      Ticketee
    <% end %>
  </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
  <div class='flash' id='<%= key %>'>
    <%= value %>
  </div>
<% end %>

<%if current_user%>
  <nav>
    <ul>
      <li><%= "Hello #{current_user.email}" %></li>
      <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
    </ul>  
  </nav>
<%else%>
  <nav>
    <ul>
      <li><%= link_to 'Sign up', new_user_registration_path %></li>
      <li><%= link_to 'Sign in', new_user_session_path %></li>
    </ul>
  </nav>
<%end%>
<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(@project.errors.count, "error") %>
       prohibited this project from being saved:</h2>
     <ul>
     <% @project.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     </ul>
   </div>
  <% end %>
  
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </p>
  <%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h2>Edit project</h2>

<%= render 'form' %>

app/views/projects/index.html.erb
<% admins_only do %>
  <%= link_to "New Project", new_project_path %>
<% end %>

<h2>Projects</h2>
<ul>
  <% @projects.each do |project| %>
    <li><%= link_to project.name, project %></li>
  <% end %>
</ul>

app/views/projects/new.html.erb
<%= render 'form' %>

app/views/projects/show.html.erb
<% title(@project.name, "Projects") %>
<h2><%= @project.name %><h2/>

<% admins_only do %>
  <%= link_to "Edit Project", edit_project_path(@project) %>

  <%= link_to "Delete Project", project_path(@project), method: :delete, data: { confirm: "Are you sure you want to delete this project?" } %>
<% end %>

<%= link_to 'New Ticket', new_project_ticket_path(@project)%>

<ul id='tickets'>
  <% @project.tickets.each do |ticket| %>
    <li>
      #<%= ticket.id %> -
      <%= link_to ticket.title, [@project, ticket] %>
    </li>
  <% end %>
</ul>

app/views/tickets/_form.html.erb
<%= form_for [@project, @ticket] do |f| %>
  <% if @ticket.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(@ticket.errors.count, "error") %>
     prohibited this ticket from being saved:</h2>
     <ul>
     <% @ticket.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     </ul>
   </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p> 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <%= f.submit %>
<% end %>

app/views/tickets/edit.html.erb
<h2>Editing a ticket in <%= @project.name %></h2>
<%= render "form" %>

app/views/tickets/new.html.erb
<h2>New Ticket</h2>

<%= render 'form' %>

app/views/tickets/show.html.erb
<div id='ticket'>
  <h2><%= @ticket.title %></h2>
  <span id='author'>Created by <%= @ticket.user.email %></span>
  <%= simple_format(@ticket.description) %>
</div>

<%= link_to "Edit Ticket", [:edit, @project, @ticket] %>

<%= link_to "Delete Ticket", [@project, @ticket], method: :delete, data: { confirm: "Are you sure you want to delete this ticket?" } %>